/**
 * Expo config plugin — M-09: certificate pinning
 *
 * Android: injects a Network Security Config (NSC) that pins the SHA-256
 * fingerprint of the API server's TLS certificate leaf or intermediate CA.
 * This prevents MITM attacks even if a rogue CA is trusted by the device.
 *
 * iOS: sets NSPinnedDomains in Info.plist (App Transport Security).
 *
 * HOW TO OBTAIN THE CERTIFICATE FINGERPRINT:
 *   openssl s_client -connect api.cloudcampus.io:443 </dev/null 2>/dev/null \
 *     | openssl x509 -pubkey -noout \
 *     | openssl pkey -pubin -outform der \
 *     | openssl dgst -sha256 -binary \
 *     | openssl enc -base64
 *
 * Set EXPO_PUBLIC_API_HOST and CERT_PIN_SHA256 in your .env / EAS secrets.
 * A backup pin (CERT_PIN_BACKUP_SHA256) is required for zero-downtime cert rotation.
 */

const { withAndroidManifest, withInfoPlist } = require('@expo/config-plugins');
const { readFileSync, writeFileSync, mkdirSync, existsSync } = require('fs');
const path = require('path');

const API_HOST        = process.env.EXPO_PUBLIC_API_HOST   ?? 'api.cloudcampus.io';
const PIN_SHA256      = process.env.CERT_PIN_SHA256        ?? 'REPLACE_WITH_LEAF_CERT_SHA256=';
const PIN_BACKUP      = process.env.CERT_PIN_BACKUP_SHA256 ?? 'REPLACE_WITH_BACKUP_CERT_SHA256=';

// ── Android Network Security Config ──────────────────────────────────────────

function withAndroidCertPin(config) {
  return withAndroidManifest(config, (modConfig) => {
    const projectRoot = modConfig.modRequest.projectRoot;
    const resXmlDir   = path.join(projectRoot, 'android', 'app', 'src', 'main', 'res', 'xml');

    if (!existsSync(resXmlDir)) mkdirSync(resXmlDir, { recursive: true });

    const nscPath = path.join(resXmlDir, 'network_security_config.xml');
    const nscXml  = `<?xml version="1.0" encoding="utf-8"?>
<!-- M-09: certificate pinning — generated by plugins/withNetworkSecurity.js -->
<!-- Re-run 'npx expo prebuild' after rotating the certificate fingerprint.  -->
<network-security-config>
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="true">${API_HOST}</domain>
    <pin-set expiration="2027-01-01">
      <!-- Primary leaf/CA public key fingerprint -->
      <pin digest="SHA-256">${PIN_SHA256}</pin>
      <!-- Backup pin required for zero-downtime cert rotation -->
      <pin digest="SHA-256">${PIN_BACKUP}</pin>
    </pin-set>
  </domain-config>
  <!-- Allow cleartext for local dev only -->
  <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;
    writeFileSync(nscPath, nscXml, 'utf-8');

    // Add networkSecurityConfig attribute to <application>
    const manifest = modConfig.modResults;
    const app      = manifest.manifest.application?.[0];
    if (app) {
      app.$                              = app.$ ?? {};
      app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return modConfig;
  });
}

// ── iOS App Transport Security (NSPinnedDomains) ──────────────────────────────

function withIosCertPin(config) {
  return withInfoPlist(config, (modConfig) => {
    const plist = modConfig.modResults;
    plist.NSAppTransportSecurity                   = plist.NSAppTransportSecurity ?? {};
    plist.NSAppTransportSecurity.NSPinnedDomains   = {
      [API_HOST]: {
        NSIncludesSubdomains:       true,
        NSPinnedLeafIdentities: [
          { SPKI_SHA256_BASE64: PIN_SHA256 },
          { SPKI_SHA256_BASE64: PIN_BACKUP },
        ],
      },
    };
    // Enforce TLS 1.2+ — disable exceptions
    plist.NSAppTransportSecurity.NSAllowsArbitraryLoads = false;
    return modConfig;
  });
}

module.exports = (config) => withIosCertPin(withAndroidCertPin(config));
