export const queryKeys = {
  students: (page: number, size: number) => ['students', page, size] as const,
  teachers: (page: number, size: number) => ['teachers', page, size] as const,
  academicClasses: ['academic', 'classes'] as const,
  academicSubjects: ['academic', 'subjects'] as const,
  academicSections: ['academic', 'sections'] as const,
  tenantDashboardSummary: ['dashboard', 'tenant-summary'] as const,
  superAdminDashboardSummary: ['super-admin', 'dashboard-summary'] as const,
  tenants: ['tenants'] as const,
  subscriptionPlans: ['subscription', 'plans'] as const,
  tenantSubscription: (tenantId: string) => ['subscription', 'tenant', tenantId] as const,
  tenantPayments: (tenantId: string) => ['payments', 'tenant', tenantId] as const,
  attendanceByDate: (date: string) => ['attendance', 'date', date] as const,
  feeAssignments: (studentId: string) => ['fees', 'assignments', studentId] as const,
  examsByClass: (classId: string) => ['exams', 'class', classId] as const,
  examResults: (examId: string) => ['exams', 'results', examId] as const,
  homeworkByClass: (classId: string) => ['homework', 'class', classId] as const,
  timetable: (classId: string, sectionId: string) => ['timetable', classId, sectionId] as const,
  parentChildren: ['parent', 'children'] as const,
  studentDashboard: ['dashboard', 'student'] as const,
  teacherDashboard: ['dashboard', 'teacher'] as const,
} as const
