package com.cloudcampus.exam.entity;

import com.cloudcampus.common.tenant.TenantFilter;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Aggregated exam result for one student (CC-1103).
 *
 * Rules:
 * - Generated by {@code ResultServiceImpl.generate()} which reads all
 *   {@link StudentMark} rows for the exam, aggregates per student, then
 *   upserts into this table.
 * - {@code rank} is 1-based, assigned by percentage DESC; tied students
 *   receive the same rank and the next rank is skipped.
 * - {@code isPassed} = percentage ≥ pass threshold derived from the exam.
 *
 * Maps to {@code exam_results} (V30__create_exam_results.sql).
 */
@Entity
@Table(name = "exam_results")
@FilterDef(
    name       = TenantFilter.NAME,
    parameters = @ParamDef(name = TenantFilter.PARAM, type = String.class)
)
@Filter(name = TenantFilter.NAME, condition = "tenant_id = :" + TenantFilter.PARAM)
public class ExamResult {

    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "tenant_id", nullable = false, updatable = false)
    private UUID tenantId;

    @Column(name = "exam_id", nullable = false, updatable = false)
    private UUID examId;

    @Column(name = "student_id", nullable = false, updatable = false)
    private UUID studentId;

    @Column(name = "school_id", nullable = false, updatable = false)
    private UUID schoolId;

    @Column(name = "total_marks_obtained", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalMarksObtained;

    @Column(name = "total_marks_possible", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalMarksPossible;

    @Column(name = "percentage", nullable = false, precision = 5, scale = 2)
    private BigDecimal percentage;

    @Column(name = "grade", nullable = false, length = 5)
    private String grade;

    @Column(name = "rank")
    private Integer rank;

    @Column(name = "is_passed", nullable = false)
    private boolean passed;

    @Column(name = "generated_at", nullable = false)
    private Instant generatedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected ExamResult() {}

    @PrePersist
    private void prePersist() {
        if (id == null) id = UUID.randomUUID();
        Instant now = Instant.now();
        if (createdAt == null) createdAt = now;
        updatedAt    = now;
        generatedAt  = now;
    }

    @PreUpdate
    private void preUpdate() {
        updatedAt   = Instant.now();
        generatedAt = Instant.now();
    }

    // ── Factory ───────────────────────────────────────────────────────────────

    public static ExamResult create(
            UUID tenantId,
            UUID examId,
            UUID studentId,
            UUID schoolId,
            BigDecimal totalMarksObtained,
            BigDecimal totalMarksPossible,
            BigDecimal percentage,
            String grade,
            boolean passed) {

        ExamResult r = new ExamResult();
        r.tenantId            = tenantId;
        r.examId              = examId;
        r.studentId           = studentId;
        r.schoolId            = schoolId;
        r.totalMarksObtained  = totalMarksObtained;
        r.totalMarksPossible  = totalMarksPossible;
        r.percentage          = percentage;
        r.grade               = grade;
        r.passed              = passed;
        return r;
    }

    // ── Behaviour ─────────────────────────────────────────────────────────────

    public void updateAggregates(
            BigDecimal totalMarksObtained,
            BigDecimal totalMarksPossible,
            BigDecimal percentage,
            String grade,
            boolean passed) {

        this.totalMarksObtained = totalMarksObtained;
        this.totalMarksPossible = totalMarksPossible;
        this.percentage         = percentage;
        this.grade              = grade;
        this.passed             = passed;
    }

    public void assignRank(int rank) {
        this.rank = rank;
    }

    // ── Getters ───────────────────────────────────────────────────────────────

    public UUID        getId()                  { return id; }
    public UUID        getTenantId()            { return tenantId; }
    public UUID        getExamId()              { return examId; }
    public UUID        getStudentId()           { return studentId; }
    public UUID        getSchoolId()            { return schoolId; }
    public BigDecimal  getTotalMarksObtained()  { return totalMarksObtained; }
    public BigDecimal  getTotalMarksPossible()  { return totalMarksPossible; }
    public BigDecimal  getPercentage()          { return percentage; }
    public String      getGrade()               { return grade; }
    public Integer     getRank()                { return rank; }
    public boolean     isPassed()               { return passed; }
    public Instant     getGeneratedAt()         { return generatedAt; }
    public Instant     getCreatedAt()           { return createdAt; }
    public Instant     getUpdatedAt()           { return updatedAt; }
}
