package com.campuscloud.subscription.entity;

public enum PlanFeature {
    STUDENT_MANAGEMENT,
    TEACHER_MANAGEMENT,
    ACADEMIC_MANAGEMENT,
    ATTENDANCE_TRACKING,
    FEE_MANAGEMENT,
    EXAM_MANAGEMENT,
    HOMEWORK_MANAGEMENT,
    TIMETABLE_MANAGEMENT,
    PARENT_PORTAL,
    BULK_UPLOAD,
    DASHBOARD_ACCESS,
    ADVANCED_REPORTS,
    CUSTOM_BRANDING
}
