-- V17: Students table — core student entity (CC-0501).
--
-- Design decisions:
--   Every student belongs to exactly one school within a tenant.
--   student_number is school-scoped unique (e.g. "2024-001", "2025-042").
--     Auto-generated by the service; can be overridden during bulk import.
--   user_id links to the users table (created on first login setup); nullable
--     because the user account may be provisioned later.
--   class_id / section_id reflect CURRENT placement — updated each term.
--     SET NULL on delete to avoid orphan breakage (placement history tracked
--     separately in a future feature).
--   status lifecycle: ACTIVE → GRADUATED / TRANSFERRED / SUSPENDED / WITHDRAWN.
--   gender and blood_group are nullable (not all schools collect them).
--   Tenant filter applied at service layer via Hibernate @Filter (tenant_id).

CREATE TABLE IF NOT EXISTS students (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID         NOT NULL REFERENCES tenants(id),
    school_id       UUID         NOT NULL REFERENCES schools(id),

    -- Optional linked user account (created when student logs in for first time).
    user_id         UUID         REFERENCES users(id) ON DELETE SET NULL,

    -- Unique student number within the school, e.g. "2024-001".
    student_number  VARCHAR(50)  NOT NULL,
    admission_date  DATE         NOT NULL DEFAULT CURRENT_DATE,
    status          VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',

    -- Current class/section placement (nullable until formally assigned).
    class_id        UUID         REFERENCES classes(id)   ON DELETE SET NULL,
    section_id      UUID         REFERENCES sections(id)  ON DELETE SET NULL,

    -- Personal details.
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    date_of_birth   DATE,
    gender          VARCHAR(30),
    blood_group     VARCHAR(10),

    -- Emergency / contact details (stored here for minors without user accounts).
    phone           VARCHAR(30),
    address         VARCHAR(500),
    photo_url       VARCHAR(500),

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_students_school_number
        UNIQUE (school_id, student_number),
    CONSTRAINT chk_students_status
        CHECK (status IN ('ACTIVE', 'GRADUATED', 'TRANSFERRED', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT chk_students_gender
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'))
);

-- Tenant-scoped student query (most JPA queries use tenant_id).
CREATE INDEX IF NOT EXISTS idx_students_tenant     ON students(tenant_id);
-- School-scoped queries (list all students for a school).
CREATE INDEX IF NOT EXISTS idx_students_school     ON students(school_id);
-- Class/section placement filters (attendance, roster views).
CREATE INDEX IF NOT EXISTS idx_students_class      ON students(class_id);
CREATE INDEX IF NOT EXISTS idx_students_section    ON students(section_id);
-- Status filter (active students for most day-to-day ops).
CREATE INDEX IF NOT EXISTS idx_students_status     ON students(school_id, status);
-- Student number lookup (profile page, ID card scanning).
CREATE INDEX IF NOT EXISTS idx_students_number     ON students(school_id, student_number);
-- Name search (partial text — full-text index added later if needed).
CREATE INDEX IF NOT EXISTS idx_students_name       ON students(school_id, first_name, last_name);
