-- V19: Staff table — all school-level employees (CC-0601 / CC-0602).
--
-- Design decisions:
--   "Staff" is the umbrella entity covering teachers, accountants, librarians,
--   hostel wardens, lab assistants, admin staff, and any other school employee.
--   The staffType column drives role-specific UI tabs (e.g. timetable for
--   TEACHER, payroll-only fields for ADMIN_STAFF).
--
--   user_id links to the users table; nullable — the login account is created
--   separately (provisioned on first login or via bulk import).
--
--   department_id is nullable (not all staff belong to an academic dept).
--     ON DELETE SET NULL to survive department soft-disables.
--
--   employeeNumber is school-scoped unique (auto-generated by service, similar
--   to student_number).
--
--   qualification and specialization capture teacher-specific profile data;
--   they are valid for all staff types but most meaningful for TEACHER.
--
--   status: ACTIVE | ON_LEAVE | RESIGNED | TERMINATED.

CREATE TABLE IF NOT EXISTS staff (
    id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID         NOT NULL REFERENCES tenants(id),
    school_id           UUID         NOT NULL REFERENCES schools(id),

    -- Optional linked user account (created separately).
    user_id             UUID         REFERENCES users(id) ON DELETE SET NULL,

    -- Optional department assignment.
    department_id       UUID         REFERENCES departments(id) ON DELETE SET NULL,

    employee_number     VARCHAR(50)  NOT NULL,
    staff_type          VARCHAR(30)  NOT NULL DEFAULT 'TEACHER',
    status              VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',

    -- Personal / professional details.
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    date_of_birth       DATE,
    gender              VARCHAR(30),
    phone               VARCHAR(30),
    email               VARCHAR(200),
    address             VARCHAR(500),
    photo_url           VARCHAR(500),

    -- Professional profile (especially relevant for teachers).
    qualification       VARCHAR(300),
    specialization      VARCHAR(300),
    joining_date        DATE         NOT NULL DEFAULT CURRENT_DATE,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_staff_school_employee_number
        UNIQUE (school_id, employee_number),
    CONSTRAINT chk_staff_type
        CHECK (staff_type IN (
            'TEACHER', 'PRINCIPAL', 'VICE_PRINCIPAL',
            'ACCOUNTANT', 'LIBRARIAN', 'LAB_ASSISTANT',
            'HOSTEL_WARDEN', 'TRANSPORT_STAFF', 'ADMIN_STAFF', 'OTHER'
        )),
    CONSTRAINT chk_staff_status
        CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'RESIGNED', 'TERMINATED')),
    CONSTRAINT chk_staff_gender
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'))
);

-- Tenant-scoped queries.
CREATE INDEX IF NOT EXISTS idx_staff_tenant        ON staff(tenant_id);
-- School-level listing.
CREATE INDEX IF NOT EXISTS idx_staff_school        ON staff(school_id);
-- Department filter (departmental roster).
CREATE INDEX IF NOT EXISTS idx_staff_department    ON staff(department_id);
-- Status filter (active staff for timetabling, attendance).
CREATE INDEX IF NOT EXISTS idx_staff_status        ON staff(school_id, status);
-- Staff type filter (list all TEACHER rows quickly).
CREATE INDEX IF NOT EXISTS idx_staff_type          ON staff(school_id, staff_type);
-- Employee number lookup (profile page, ID card).
CREATE INDEX IF NOT EXISTS idx_staff_emp_number    ON staff(school_id, employee_number);
-- Name search.
CREATE INDEX IF NOT EXISTS idx_staff_name          ON staff(school_id, first_name, last_name);
