package com.cloudcampus.student.entity;

import com.cloudcampus.common.tenant.TenantFilter;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.Filter;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Core student record for a school.
 *
 * Rules:
 * - student_number is unique within (school_id) — auto-generated by the
 *   service layer unless explicitly provided.
 * - class_id / section_id hold the CURRENT placement and may be null before
 *   formal assignment (e.g. newly admitted but not yet placed).
 * - user_id is nullable — the login account is provisioned separately or on
 *   first login.
 * - status lifecycle: ACTIVE → GRADUATED | TRANSFERRED | SUSPENDED | WITHDRAWN.
 *   SUSPENDED may revert to ACTIVE.
 *
 * Maps to {@code students} table (V17__create_students.sql).
 */
@Entity
@Table(
        name = "students",
        uniqueConstraints = @UniqueConstraint(
                name = "uq_students_school_number",
                columnNames = {"school_id", "student_number"}
        )
)
@Filter(name = TenantFilter.NAME, condition = TenantFilter.CONDITION)
public class Student {

    @Id
    private UUID id;

    @Column(name = "tenant_id", nullable = false, updatable = false)
    private UUID tenantId;

    @Column(name = "school_id", nullable = false, updatable = false)
    private UUID schoolId;

    /** Optional — linked when a user account is created for this student. */
    @Column(name = "user_id")
    private UUID userId;

    /** School-generated unique identifier, e.g. "2024-001". */
    @Column(name = "student_number", nullable = false, length = 50)
    private String studentNumber;

    @Column(name = "admission_date", nullable = false)
    private LocalDate admissionDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private StudentStatus status;

    /** Current class placement — may be null until formally assigned. */
    @Column(name = "class_id")
    private UUID classId;

    /** Current section placement — may be null until formally assigned. */
    @Column(name = "section_id")
    private UUID sectionId;

    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Enumerated(EnumType.STRING)
    @Column(name = "gender", length = 30)
    private Gender gender;

    @Column(name = "blood_group", length = 10)
    private String bloodGroup;

    @Column(name = "phone", length = 30)
    private String phone;

    @Column(name = "address", length = 500)
    private String address;

    @Column(name = "photo_url", length = 500)
    private String photoUrl;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected Student() {}

    @PrePersist
    void onPersist() {
        if (id            == null) id            = UUID.randomUUID();
        if (status        == null) status        = StudentStatus.ACTIVE;
        if (admissionDate == null) admissionDate = LocalDate.now();
        if (createdAt     == null) createdAt     = Instant.now();
        updatedAt = Instant.now();
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }

    // -------------------------------------------------------------------------
    // Factory
    // -------------------------------------------------------------------------

    /**
     * Creates a new {@link Student} record ready to be persisted.
     *
     * @param tenantId      owning tenant
     * @param schoolId      school the student is being admitted to
     * @param studentNumber unique number within the school (pre-generated)
     * @param firstName     given name
     * @param lastName      family name
     * @param admissionDate date of formal admission (defaults to today if null)
     */
    public static Student create(UUID tenantId, UUID schoolId,
                                  String studentNumber,
                                  String firstName, String lastName,
                                  LocalDate admissionDate) {
        Student s = new Student();
        s.tenantId      = tenantId;
        s.schoolId      = schoolId;
        s.studentNumber = studentNumber;
        s.firstName     = firstName;
        s.lastName      = lastName;
        s.admissionDate = admissionDate != null ? admissionDate : LocalDate.now();
        return s;
    }

    // -------------------------------------------------------------------------
    // Setters (mutators used during update / profile-fill)
    // -------------------------------------------------------------------------

    public void setUserId(UUID userId)              { this.userId       = userId; }
    public void setClassId(UUID classId)            { this.classId      = classId; }
    public void setSectionId(UUID sectionId)        { this.sectionId    = sectionId; }
    public void setFirstName(String firstName)      { this.firstName    = firstName; }
    public void setLastName(String lastName)        { this.lastName     = lastName; }
    public void setDateOfBirth(LocalDate dob)       { this.dateOfBirth  = dob; }
    public void setGender(Gender gender)            { this.gender       = gender; }
    public void setBloodGroup(String bloodGroup)    { this.bloodGroup   = bloodGroup; }
    public void setPhone(String phone)              { this.phone        = phone; }
    public void setAddress(String address)          { this.address      = address; }
    public void setPhotoUrl(String photoUrl)        { this.photoUrl     = photoUrl; }
    public void setStatus(StudentStatus status)     { this.status       = status; }
    public void setStudentNumber(String num)        { this.studentNumber = num; }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    public UUID          getId()            { return id; }
    public UUID          getTenantId()      { return tenantId; }
    public UUID          getSchoolId()      { return schoolId; }
    public UUID          getUserId()        { return userId; }
    public String        getStudentNumber() { return studentNumber; }
    public LocalDate     getAdmissionDate() { return admissionDate; }
    public StudentStatus getStatus()        { return status; }
    public UUID          getClassId()       { return classId; }
    public UUID          getSectionId()     { return sectionId; }
    public String        getFirstName()     { return firstName; }
    public String        getLastName()      { return lastName; }
    public LocalDate     getDateOfBirth()   { return dateOfBirth; }
    public Gender        getGender()        { return gender; }
    public String        getBloodGroup()    { return bloodGroup; }
    public String        getPhone()         { return phone; }
    public String        getAddress()       { return address; }
    public String        getPhotoUrl()      { return photoUrl; }
    public Instant       getCreatedAt()     { return createdAt; }
    public Instant       getUpdatedAt()     { return updatedAt; }
}
